# Generated by Django 3.2.8 on 2021-10-29 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='obj',
            field=models.FileField(blank=True, null=True, upload_to='product_obj', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj'])]),
        ),
    ]
