# Generated by Django 3.2.8 on 2021-10-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='echo_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
