# Generated by Django 3.2.8 on 2021-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211101_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='echo_ar_qr',
            field=models.ImageField(blank=True, null=True, upload_to='echo_qr_codes/'),
        ),
    ]
